apiVersion: v1
kind: ConfigMap
metadata:
  name: devtools-config
  namespace: devtools
data:
  NODE_ENV: production
  PORT: "3000"
  MONGO_URI: mongodb://mongo:27017/devtools
  JWT_EXPIRES_IN: 12h
  ADMIN_USERNAME: admin
  CORS_ORIGIN: "*"
